package fr.simplex_software.aws.lambda.items;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import fr.simplex_software.eip.money_transfer.jaxb.*;

import java.math.*;

@DynamoDBTable(tableName = "MoneyTransferOrders")
public class MoneyTransferOrderItem
{
  private String id;
  private String reference;
  private BankAccount sourceBankAccount;
  private BankAccount targetBankAccount;
  private BigDecimal amount;

  public MoneyTransferOrderItem() {}

  public MoneyTransferOrderItem (MoneyTransfer moneyTransfer)
  {
    this.amount = moneyTransfer.getAmount();
    this.reference = moneyTransfer.getReference();
    this.sourceBankAccount = moneyTransfer.getSourceAccount();
    this.targetBankAccount = moneyTransfer.getTargetAccount();
  }

  @DynamoDBHashKey(attributeName = "Id")
  @DynamoDBAutoGeneratedKey
  public String getId()
  {
    return id;
  }

  public void setId(String id)
  {
    this.id = id;
  }

  @DynamoDBAttribute(attributeName="reference")
  public String getReference()
  {
    return reference;
  }

  public void setReference(String reference)
  {
    this.reference = reference;
  }

  @DynamoDBAttribute(attributeName="sourceBankAccount")
  public BankAccount getSourceBankAccount()
  {
    return sourceBankAccount;
  }

  public void setSourceBankAccount(BankAccount sourceBankAccount)
  {
    this.sourceBankAccount = sourceBankAccount;
  }

  @DynamoDBAttribute(attributeName="targetBankAccount")
  public BankAccount getTargetBankAccount()
  {
    return targetBankAccount;
  }

  public void setTargetBankAccount(BankAccount targetBankAccount)
  {
    this.targetBankAccount = targetBankAccount;
  }

  @DynamoDBAttribute(attributeName="amount")
  public BigDecimal getAmount()
  {
    return amount;
  }

  public void setAmount(BigDecimal amount)
  {
    this.amount = amount;
  }
}
