AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Chapter 9 samples
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 10
    Tracing: Active
Parameters:
  Email:
    Type: String
  Version:
    Type: String
    Default: v1
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: CognitoUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: true
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
  CognitoUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      Username: !Ref Email
      UserPoolId: !Ref CognitoUserPool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: CognitoUserPoolClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServiceApi
      StageName: !Ref Version
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "CognitoUserPool.Arn"
  SecureLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SecureLambdaFunction
      Description: Requires authentication to handle request
      Handler: fr.simplex_software.aws.lambda.cognito.functions.SecureLambdaFunction::handleRequest
      CodeUri: target/chapter9.jar
      # Policies:
      Events:
        Get:
          Type: Api
          Properties:
            Path: /secure
            RestApiId: !Ref ServiceApi
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer
  OpenLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OpenLambdaFunction
      Description: Handles the request with no need for authentication
      Handler: fr.simplex_software.aws.lambda.cognito.functions.OpenLambdaFunction::handleRequest
      CodeUri: target/chapter9.jar
      Events:
        Get:
          Type: Api
          Properties:
            Path: /open
            RestApiId: !Ref ServiceApi
            Method: GET
Outputs:
  CognitoID:
    Description: The Cognito UserPool ID
    Value: !Ref CognitoUserPool
  CognitoClientID:
    Description: The Cognito UserPool Client ID
    Value: !Ref CognitoUserPoolClient
  ApiUrl:
    Description: The API URL
    Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${Version}"
