AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Chapter 9 samples
Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 10
    Tracing: Active
Parameters:
  Version:
    Type: String
    Default: v1
Resources:
  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServiceApi
      StageName: !Ref Version
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  SecureLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SecureLambdaFunction
      Description: Requires authentication to handle request
      Handler: fr.simplex_software.aws.lambda.cognito.functions.SecureLambdaFunction::handleRequest
      CodeUri: target/chapter9.jar
      Events:
        Get:
          Type: Api
          Properties:
            Path: /secure
            RestApiId: !Ref ServiceApi
            Method: GET
            Auth:
              ResourcePolicy:
                CustomStatements: [{
                  "Effect": "Allow",
                  "Principal": { "AWS": "arn:aws:iam::459436678662:user/seymourglass" },
                  "Action": "execute-api:Invoke",
                  "Resource": "execute-api:/*/GET/secure",
                }]
  OpenLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: OpenLambdaFunction
      Description: Handles the request with no need for authentication
      Handler: fr.simplex_software.aws.lambda.cognito.functions.OpenLambdaFunction::handleRequest
      CodeUri: target/chapter9.jar
      Events:
        Get:
          Type: Api
          Properties:
            Path: /open
            RestApiId: !Ref ServiceApi
            Method: GET
            Auth:
              ResourcePolicy:
                CustomStatements: [{
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "execute-api:Invoke",
                  "Resource": "execute-api:/*/GET/*",
                }]
Outputs:
  ApiUrl:
    Description: The API URL
    Value: !Sub "https://${ServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${Version}"
