AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Chapter 5 Sample

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 10
Parameters:
  BucketName:
    Type: String
    Description: The name of the input S3 bucket
Resources:
  SendMoneyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  FilePollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FilePollerFunction
      CodeUri: target/chapter5.jar
      Handler: fr.simplex_software.aws.lambda.s3.functions.FilePoller::handleRequest
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SendMoneyBucket
            Events: s3:ObjectCreated:*
